version: '3.8'

services:
  meilisearch:
    image: getmeili/meilisearch:v1.33.1
    # image: getmeili/meilisearch:latest
    container_name: opencubee2_meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_HTTP_ADDR=0.0.0.0:7700
      - MEILI_SERVER_PROVIDER=docker
    volumes:
      - /GuestShare_NAS/WorkingSpace/Personal/nguyenmv/HCMAIC2026/AICHALLENGE_OPENCUBEE_2/Opencubee2/database/meilisearch/storage:/meili_data
      # - /workingspace_aiclub/WorkingSpace/Personal/nguyenmv/Opencubee2_HCMAI25/Opencubee2/database/meilisearch/storage:/meili_data

