services:
  ui:
    build:
      context: .
      args:
        VITE_BACKEND_BASE_URL: ${VITE_BACKEND_BASE_URL:-http://localhost:21081}
        VITE_ASSET_BASE_URL: ${VITE_ASSET_BASE_URL:-/keyframes}
    image: opencubee2-ui-nginx
    ports:
      - "21080:21080"
